
server:
  port: 9010


#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:9050/eureka/
#  instance:
#    hostname: localhost


spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: mongodb://192.168.27.8:27017/category-db

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
        defaultQueryParameters:
          query: queryValue
          defaultRequestHeaders:
            header: headerValue
#          requestInterceptors:
#            - org.helpdesk.category.config.FeignClientInterceptorPostService

open-feign-clients:
  post-service:
    name: post-service
    base-url: http://localhost:9011/api
    methods:
      get-posts-with-given-category-id: /posts #getPostsWithGivenCategoryId
