server:
  port: 9013

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: newPost
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: <host>
                port: 5672
                username: <username>
                password: <password>
                virtual-host: /

